### ISSUE TITLE
which version of  comfy

### ISSUE THREAD

**Issue by skydh** [Jannchie/ComfyUI-J#11]

**Comment by Jannchie** [comment]
The latest version of the comfy master branch should be able to run.

**Comment by skydh** [comment]
compel version

**Comment by skydh** [comment]
Traceback (most recent call last):
  File "/mnt/workspace/aaa/ComfyUI/custom_nodes/ComfyUI-J/__init__.py", line 7, in <module>
    from compel import Compel, DiffusersTextualInversionManager
ModuleNotFoundError: No module named 'compel'

**Comment by skydh** [comment]
i copy this file can do success，but  run this file ,get error

**Comment by skydh** [comment]
soryy, i have fixed it, it because aliyun pai bug，Speechless

**Comment by skydh** [comment]
thank you
