### ISSUE TITLE
Error in diffuser generator-- using example workflow -basic

### ISSUE THREAD

**Issue by jags111** [Jannchie/ComfyUI-J#14]
i tried several times using same workflow.. But every time it is not getting past this
#14 [DiffusersGenerator]: 0.95s
Prompt executed in 1.16 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
Prompt executor has been patched by Job Iterator!
#3 [DiffusersCompelPromptEmbedding]: 0.22s
torch.bfloat16 torch.bfloat16
!!! Exception during processing !!!
Traceback (most recent call last):
  File "I:\AI\comfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\AI\comfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\AI\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 381, in new_func
    res_value = old_func(*final_args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\AI\comfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\AI\ComfyUI\custom_nodes\ComfyUI-J\__init__.py", line 841, in run
    result = pipeline(
             ^^^^^^^^^
  File "I:\AI\comfyUI\venv\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "I:\AI\ComfyUI\custom_nodes\ComfyUI-J\pipelines\jannchie.py", line 498, in __call__
    added_cond_kwargs["text_embeds"] = prompt_embeds
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment

#14 [DiffusersGenerator]: 0.87s
Prompt executed in 1.13 seconds

**Comment by jags111** [comment]
<img width="1081" alt="2024-05-01_12-17-29" src="https://github.com/Jannchie/ComfyUI-J/assets/5968619/fc18e57f-ccc2-4580-928a-2bc6c65269d2">

**Comment by Jannchie** [comment]
My mistake. I just pushed the new code, you can try again.

**Comment by jags111** [comment]
okay all good
tested and working now
<img width="1042" alt="2024-05-01_13-19-33" src="https://github.com/Jannchie/ComfyUI-J/assets/5968619/eefab29d-d69b-4e49-999a-38e138cb39f4">

**Comment by jags111** [comment]
<img width="1050" alt="2024-05-01_13-22-15" src="https://github.com/Jannchie/ComfyUI-J/assets/5968619/add82328-5355-4775-a1b2-d3de8376ed50">

**Comment by jags111** [comment]
almost all nodes work perfectly and change clothes is also very cool... 
<img width="979" alt="2024-05-01_14-52-00" src="https://github.com/Jannchie/ComfyUI-J/assets/5968619/eab7db17-bf58-47fc-9993-13f67b5aa969">
