### ISSUE TITLE
error report no module error

### ISSUE THREAD

**Issue by quqiufeng** [Jannchie/ComfyUI-J#15]
Cannot import D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-J module for custom nodes: No module named 'diffusers.models.unets'

![image](https://github.com/Jannchie/ComfyUI-J/assets/839168/7f691646-94f0-42bf-8f27-4145fdb9c2a6)

**Comment by quqiufeng** [comment]
![image](https://github.com/Jannchie/ComfyUI-J/assets/839168/22f2c2b6-77ba-4fa8-b8cf-af583726f3ce)

diffusers is installed

**Comment by Jannchie** [comment]
The version of diffusers you might have installed could be outdated, or perhaps you have not correctly installed diffusers into the Python virtual environment used by comfy.
