### ISSUE TITLE
your workflow in open art  has an issue

### ISSUE THREAD

**Issue by quqiufeng** [Jannchie/ComfyUI-J#17]
https://openart.ai/workflows/frog_forsaken_49/change-clothes/siND9pTFXEUumY1qYEXq  

![image](https://github.com/Jannchie/ComfyUI-J/assets/839168/24dce608-d601-48d5-9fc6-4d8d9bfca549)

The newly generated image is masked in gray
how to fix this?

**Comment by Jannchie** [comment]
Generally, this is caused by a VAE mismatch. You could try using a different VAE.

**Comment by quqiufeng** [comment]
![image](https://github.com/Jannchie/ComfyUI-J/assets/839168/4657f43e-6600-43e5-be94-f93c7ddd2db6)
same as your workflow
sometimes it's ok

**Comment by quqiufeng** [comment]
还是一层灰色在上面  博主不解决么？

**Comment by Jannchie** [comment]
You are **NOT** using the same checkpoint.

I don’t know where you downloaded the model from. Although the names are similar, the model you are using is different and requires an additional VAE. Please look for the cause within yourself.
