### ISSUE TITLE
Get average color not working

### ISSUE THREAD

**Issue by ManuelStp** [Jannchie/ComfyUI-J#28]
Hi!

I get this error when executing the node and connecting an output to it. Am I doing something wrong? I just can't figure it out.

"
Error occurred when executing GetAverageColorFromImage:

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

"

The input is an rgb .png image

![image](https://github.com/user-attachments/assets/1e33aa18-4366-48ff-86cb-e680caa66c9e)

Thanks in advance!

**Comment by Jannchie** [comment]
Perhaps the version update of comfyUI caused the incompatibility. I’ll check it out later to see what’s going on.

**Comment by ManuelStp** [comment]
Thank you!

**Comment by Jannchie** [comment]
I have fixed the issue. You can try again by getting the latest version.
