### ISSUE TITLE
Readme typos

### ISSUE THREAD

**Issue by ItsDyze** [Jannchie/ComfyUI-J#3]
Two small typos in the readme:

Git clone instructions are missing the https to be able to run without issue.
```bash
git clone https://github.com/Jannchie/ComfyUI-J.git
cd ComfyUI-J
pip install -r requirements.txt
```

Your search for a good Reference Only implementation took longer than expected (2042)
"it's 2024 and I still haven't found a good Reference Only implementation"

**Comment by Jannchie** [comment]
Thanks for correction！

> Your search for a good Reference Only implementation took longer than expected (2042)

lol it's a joke

**Comment by Jannchie** [comment]
I've fixed the git clone address!
